services:
  web-interface:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    env_file:
      - .env

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env